name: flutter_material_color_system
description: Material Design 3 のカラーシステムを確認できるサイトです。配色に悩んだときにご利用ください。
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hexcolor: ^3.0.1
  material_color_utilities: ^0.5.0
  responsive_framework: ^0.2.0
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.5.3
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  web:
    generate: true
    image_path: 'assets/images/app-icon.png'
    background_color: '#ffffff'
    theme_color: '#6750A4'

flutter_gen:
  output: lib/util/assets/
  integrations:
    flutter_svg: true
