name: flutter_material_color_tonal_palettes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flex_color_picker: ^3.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  hexcolor: ^3.0.1
  material_color_utilities: ^0.2.0
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.4
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.21.1
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true
