name: flutter_material_color_system
description: Material Design 3 のカラーシステムを確認できるサイトです。配色に悩んだときにご利用ください。
publish_to: 'none'
version: '3.1.0'
environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  collection:
  cupertino_icons:
  flex_color_picker:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  gap:
  hexcolor:
  hive:
  hive_flutter:
  material_color_utilities:
  package_info_plus:
  recase:
  responsive_framework: 0.2.0
  riverpod_annotation:
  roggle:
  shared_preferences:
  url_launcher:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .dart_tool/version

flutter_launcher_icons:
  web:
    generate: true
    image_path: 'assets/images/app-icon.png'
    background_color: '#ffffff'
    theme_color: '#6750A4'

flutter_gen:
  output: lib/util/assets/
  integrations:
    flutter_svg: true
