name: flutter_material_color_system
description: Material Design 3 のカラーシステムを確認できるサイトです。配色に悩んだときにご利用ください。
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: any
  cupertino_icons: any
  flex_color_picker: any
  flutter:
    sdk: flutter
  flutter_riverpod: any
  freezed_annotation: any
  gap: any
  hexcolor: any
  hive: any
  hive_flutter: any
  material_color_utilities: any
  recase: any
  responsive_framework: 0.2.0
  riverpod_annotation: any
  roggle: any
  shared_preferences: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  custom_lint: any
  flutter_gen_runner: any
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  freezed: any
  hive_generator: any
  pedantic_mono: any
  riverpod_generator: 2.3.3
  riverpod_lint: 2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  web:
    generate: true
    image_path: 'assets/images/app-icon.png'
    background_color: '#ffffff'
    theme_color: '#6750A4'

flutter_gen:
  output: lib/util/assets/
  integrations:
    flutter_svg: true
